# General
spring.application.name=car-rental-system

spring.profiles.active=dev

# Redis Config

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.username=default

# Java Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${JAVA_MAIL_USERNAME}
spring.mail.password=${JAVA_MAIL_PASSWORD}

# File Upload Settings
car.upload.dir=uploads/
spring.web.resources.static-locations=file:uploads/,classpath:/static/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB


spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
# ===============================================
# JWT (JSON Web Token) Configuration
# ===============================================

#your-super-secret-key-that-is-long-and-random-5v8yB-EH-MbQeThVmYq3t6w9z
jwt.secret=${JWT_SECRET}

# This is the token's validity period in milliseconds.
# 3600000ms = 1 hour
jwt.expiration.ms=3600000

